### ISSUE TITLE
File Configuration

### ISSUE THREAD

**Issue by joeyahines** [joeyahines/cerial#2]
Allow args to read from a config file. This would allow users to define `profiles` they could then use to easily open ports.

```toml
[usb_serial]
dev = "/dev/ttyS0"
....
```
